### ISSUE TITLE
Node view and editor schema support

### ISSUE THREAD

**Issue by doodlewind** [BetaSu/my-vue-editor#2]
Hi, I come from your post on juejin.im, this library can be promising!

Currently I haven't found two features from the README, which can be essential to customize an editor from ground:

* **Support of custom editor nodes.** Say we have an `attachment` node type, can this editor support Vue.js components as node view? I've been using [Slate.js](https://github.com/ianstormtaylor/slate) for quite a while, its support of using React's functional components as editor nodes is awesome. For Vue's tech stack I haven't found any competing libs working on this. Is such idea possible for this project?
* **Support of "schema" for document format.** Say we have table node with `block` type and link node with `inline` type, it'll make sense to enforce the rules that `block` can contain `inline` but `inline` shouldn't contain `block`, this can greatly sanitize the doc format. The rule set can then combined as a schema for developers to tailor.

I'm not sure if this editor is designed to support such features, if it only works as a thin wrapper of `execCommand`, implementing them may require more work.

Anyway this library looks quite interesting for me. Hope for your reply!

**Comment by BetaSu** [comment]
既然是国人，那我就用中文吧。这两点在当前的编辑器中都没有实现，因为当前的编辑器主要是重写了原生的`execCommand`方法。
Slate实现的Node接口，还有大量基础操作range的方法，基于这些构建的输入--schema--输出整个流程，简直是一整套类mvc架构了，我只能说
![image](https://user-images.githubusercontent.com/15828041/34146317-805c356e-e4d4-11e7-8fba-ddb44aa4fcd4.png)
真是很有野心的一个富文本编辑器框架。
如果要在Vue技术栈实现类似功能的编辑器，第一个问题支持倒不难，只是没有React render函数方便，主要难点应该是Vue技术栈一般没有基于不可变类型数据的惯例吧。
总之，我要好好拜读下Slate的源码，这个理念让我印象深刻，感谢你提的建议，提前祝：元旦快乐～

**Comment by doodlewind** [comment]
💃💃💃
